name: deploy-github-pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: "get code"
        uses: actions/checkout@v4

      - name: "setup emsdk"
        uses: emscripten-core/setup-emsdk@v15

      - name: "build"
        run: emcc backend/main.c backend/src/* -I backend/include -o frontend/engine.js -sSTACK_SIZE=5000000

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

